In [1]:
import  pandas as pd
import numpy as np

In [2]:
data1 = pd.read_csv('StudentsPerformance.csv')

In [3]:
data1.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
data1.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
x=data1.rename(columns={'race/ethnicity':"Groups"},inplace=True)
print(x)

None

In [6]:
data1.head()

,gender,Groups,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [7]:
data1['parental level of education'].nunique()

6

In [8]:
data1['Groups'].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [9]:
data1['Groups'].nunique()

5

In [10]:
Groups = data1.groupby('Groups')

In [11]:
for x,data in Groups:
    print(x)
    print(data)

group A
     gender   Groups parental level of education         lunch  \
3      male  group A          associate's degree  free/reduced
13     male  group A                some college      standard
14   female  group A             master's degree      standard
25     male  group A             master's degree  free/reduced
46   female  group A          associate's degree      standard
..      ...      ...                         ...           ...
974  female  group A                some college      standard
983  female  group A                some college      standard
985    male  group A                 high school      standard
988  female  group A            some high school  free/reduced
994    male  group A                 high school      standard

    test preparation course  math score  reading score  writing score
3                      none          47             57             44
13                completed          78             72             70
14                     none          50             53             58
25                     none          73             74             72
46                completed          55             65             62
..                      ...         ...            ...            ...
974                    none          54             63             67
983               completed          78             87             91
985                    none          57             51             54
988                    none          44             45             45
994                    none          63             63             62

[89 rows x 8 columns]
group B
     gender   Groups parental level of education         lunch  \
0    female  group B           bachelor's degree      standard
2    female  group B             master's degree      standard
5    female  group B          associate's degree      standard
6    female  group B                some college      standard
7      male  group B                some college  free/reduced
..      ...      ...                         ...           ...
969  female  group B           bachelor's degree      standard
976    male  group B                some college  free/reduced
980  female  group B                 high school  free/reduced
982    male  group B            some high school      standard
991  female  group B            some high school      standard

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
2                      none          90             95             93
5                      none          71             83             78
6                 completed          88             95             92
7                      none          40             43             39
..                      ...         ...            ...            ...
969                    none          75             84             80
976               completed          60             62             60
980                    none           8             24             23
982               completed          79             85             86
991               completed          65             82             78

[190 rows x 8 columns]
group C
     gender   Groups parental level of education         lunch  \
1    female  group C                some college      standard
4      male  group C                some college      standard
10     male  group C          associate's degree      standard
15   female  group C            some high school      standard
16     male  group C                 high school      standard
..      ...      ...                         ...           ...
979  female  group C          associate's degree      standard
984  female  group C            some high school      standard
986  female  group C          associate's degree      standard
996    male  group C                 high school  free/reduced
997  female  group C                 high school  free/reduced

    test preparation course  math score  reading score  writing score
1                 completed          69             90             88
4                      none          76             78             75
10                     none          58             54             52
15                     none          69             75             78
16                     none          88             89             86
..                      ...         ...            ...            ...
979                    none          91             95             94
984                    none          74             75             82
986                    none          40             59             51
996                    none          62             55             55
997               completed          59             71             65

[319 rows x 8 columns]
group D
     gender   Groups parental level of education         lunch  \
8      male  group D                 high school  free/reduced
11     male  group D          associate's degree      standard
20     male  group D                 high school      standard
22     male  group D                some college      standard
24     male  group D           bachelor's degree  free/reduced
..      ...      ...                         ...           ...
989  female  group D                some college  free/reduced
992  female  group D          associate's degree  free/reduced
993  female  group D           bachelor's degree  free/reduced
998  female  group D                some college      standard
999  female  group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
8                 completed          64             64             67
11                     none          40             52             43
20                     none          66             69             63
22                     none          44             54             53
24                completed          74             71             80
..                      ...         ...            ...            ...
989               completed          67             86             83
992                    none          55             76             76
993                    none          62             72             74
998               completed          68             78             77
999                    none          77             86             86

[262 rows x 8 columns]
group E
     gender   Groups parental level of education         lunch  \
32   female  group E             master's degree  free/reduced
34     male  group E                some college      standard
35     male  group E          associate's degree      standard
44   female  group E          associate's degree  free/reduced
50     male  group E                some college      standard
..      ...      ...                         ...           ...
962  female  group E          associate's degree      standard
968  female  group E          associate's degree      standard
987    male  group E            some high school      standard
990    male  group E                 high school  free/reduced
995  female  group E             master's degree      standard

    test preparation course  math score  reading score  writing score
32                     none          56             72             65
34                     none          97             87             82
35                completed          81             81             79
44                     none          50             56             54
50                     none          53             55             48
..                      ...         ...            ...            ...
962                    none         100            100            100
968                    none          68             76             67
987               completed          81             75             76
990               completed          86             81             75
995               completed          88             99             95

[140 rows x 8 columns]

In [12]:
Groups.max(numeric_only=True)

         math score  reading score  writing score
Groups
group A         100            100             97
group B          97             97             96
group C          98            100            100
group D         100            100            100
group E         100            100            100

In [13]:
Groups.min(numeric_only=True)

         math score  reading score  writing score
Groups
group A          28             23             19
group B           8             24             15
group C           0             17             10
group D          26             31             32
group E          30             26             22

In [14]:
Groups.count()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score
Groups,,,,,,,
group A,89,89,89,89,89,89,89
group B,190,190,190,190,190,190,190
group C,319,319,319,319,319,319,319
group D,262,262,262,262,262,262,262
group E,140,140,140,140,140,140,140

## Practice

In [15]:
Groups['math score'].sum().sort_values(ascending=False).head(1)

Groups
group C    20564
Name: math score, dtype: int64

In [16]:
Groups['writing score'].mean().sort_values().head(1)

Groups
group A    62.674157
Name: writing score, dtype: float64

In [17]:
Groups['reading score'].max().sort_values()

Groups
group B     97
group A    100
group C    100
group D    100
group E    100
Name: reading score, dtype: int64

In [19]:
data1.groupby('parental level of education').groups

{'associate's degree': [3, 5, 10, 11, 19, 35, 36, 38, 39, 40, 41, 42, 44, 45, 46, 48, 51, 56, 57, 62, 63, 68, 69, 72, 75, 80, 83, 87, 93, 95, 102, 107, 108, 110, 112, 121, 138, 147, 149, 152, 158, 159, 160, 173, 177, 183, 185, 190, 195, 200, 202, 203, 213, 216, 221, 224, 231, 235, 239, 245, 246, 256, 257, 268, 272, 285, 286, 290, 295, 297, 299, 302, 303, 304, 308, 310, 313, 317, 319, 328, 331, 332, 333, 337, 343, 349, 353, 356, 375, 380, 381, 387, 393, 397, 406, 407, 409, 412, 417, 420, ...], 'bachelor's degree': [0, 24, 27, 60, 77, 90, 99, 101, 114, 116, 117, 120, 129, 134, 135, 148, 151, 153, 165, 174, 189, 199, 206, 232, 234, 236, 241, 266, 270, 275, 279, 282, 288, 293, 311, 312, 314, 318, 334, 347, 350, 355, 365, 367, 374, 379, 386, 414, 416, 426, 455, 456, 458, 460, 464, 475, 476, 493, 507, 509, 522, 528, 535, 538, 551, 562, 564, 566, 569, 571, 582, 587, 592, 594, 595, 612, 616, 617, 621, 624, 632, 645, 667, 692, 697, 700, 702, 705, 740, 748, 757, 771, 773, 784, 809, 816, 817, 821, 831, 832, ...], 'high school': [8, 9, 12, 16, 20, 28, 47, 49, 53, 55, 81, 84, 91, 92, 103, 111, 115, 123, 125, 137, 143, 156, 163, 166, 168, 170, 176, 182, 186, 197, 207, 212, 214, 217, 218, 220, 227, 240, 242, 247, 248, 249, 254, 263, 264, 267, 277, 280, 281, 294, 298, 309, 315, 320, 321, 324, 330, 340, 341, 342, 345, 348, 360, 366, 388, 395, 396, 403, 404, 408, 415, 419, 421, 431, 432, 438, 441, 447, 448, 459, 467, 468, 471, 480, 483, 485, 494, 495, 506, 519, 524, 527, 534, 537, 540, 547, 548, 568, 573, 574, ...], 'master's degree': [2, 14, 18, 25, 29, 32, 79, 106, 128, 130, 162, 164, 167, 175, 178, 180, 194, 225, 253, 259, 316, 377, 382, 389, 410, 422, 478, 500, 504, 508, 514, 523, 544, 549, 557, 567, 579, 600, 604, 607, 618, 685, 713, 735, 752, 781, 789, 812, 845, 846, 850, 861, 892, 900, 901, 940, 941, 957, 995], 'some college': [1, 4, 6, 7, 13, 21, 22, 26, 30, 31, 33, 34, 43, 50, 52, 58, 67, 70, 71, 82, 85, 86, 88, 94, 97, 98, 100, 104, 105, 113, 119, 122, 124, 127, 132, 133, 139, 141, 142, 144, 145, 155, 157, 161, 169, 172, 181, 191, 193, 198, 201, 204, 208, 209, 211, 226, 229, 230, 238, 243, 251, 255, 258, 261, 269, 271, 273, 274, 283, 300, 305, 306, 322, 325, 326, 327, 335, 344, 346, 351, 352, 354, 357, 358, 359, 362, 364, 370, 371, 373, 385, 391, 392, 401, 402, 411, 418, 424, 425, 435, ...], 'some high school': [15, 17, 23, 37, 54, 59, 61, 64, 65, 66, 73, 74, 76, 78, 89, 96, 109, 118, 126, 131, 136, 140, 146, 150, 154, 171, 179, 184, 187, 188, 192, 196, 205, 210, 215, 219, 222, 223, 228, 233, 237, 244, 250, 252, 260, 262, 265, 276, 278, 284, 287, 289, 291, 292, 296, 301, 307, 323, 329, 336, 338, 339, 361, 363, 368, 369, 372, 376, 378, 383, 384, 390, 394, 398, 399, 400, 405, 413, 423, 427, 428, 429, 433, 434, 439, 442, 444, 445, 473, 488, 498, 505, 511, 512, 513, 515, 518, 526, 531, 545, ...]}

In [ ]:
data1.iloc[149]  #

gender                                       male
Groups                                    group E
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                 completed
math score                                    100
reading score                                 100
writing score                                  93
Name: 149, dtype: object

In [22]:
# size()
data1.groupby('Groups').size()

Groups
group A     89
group B    190
group C    319
group D    262
group E    140
dtype: int64

In [23]:
Groups['lunch'].nunique()

Groups
group A    2
group B    2
group C    2
group D    2
group E    2
Name: lunch, dtype: int64

## custom aggregation

In [24]:
parent=data1.groupby('parental level of education')

In [25]:
parent.agg(
    {
        'math score':'mean',
        'reading score':'std'
    }
)

                             math score  reading score
parental level of education
associate's degree            67.882883      13.868948
bachelor's degree             69.389831      14.285250
high school                   62.137755      14.132130
master's degree               69.745763      13.775163
some college                  67.128319      14.057049
some high school              63.497207      15.479295

In [26]:
parent.agg(
    {
        'math score':['mean','min'],
        'reading score':'std',
        
    }
)

                            math score     reading score
                                  mean min           std
parental level of education
associate's degree           67.882883  26     13.868948
bachelor's degree            69.389831  29     14.285250
high school                  62.137755   8     14.132130
master's degree              69.745763  40     13.775163
some college                 67.128319  19     14.057049
some high school             63.497207   0     15.479295